### ISSUE TITLE
install.inf installs wrong cursors & large size is switched to regular size

### ISSUE THREAD

**Issue by CtrlAltDelicious01** [ful1e5/apple_cursor#107] opened 2024-06-19 03:01 UTC
- The **regular sized cursors are switched to the large folder**, and the **large cursors are switched to the regular folder**.
- Upon installing from `macOS-Large-Windows` using `install.inf`, the installer switches `Link.cur` with `Pan.cur`.
![image](https://github.com/ful1e5/apple_cursor/assets/74717237/576404b3-f0b3-46a5-96c3-db244eb93d51)

These are the issues I've found as of `v2.0.1`

**Comment by k2s09** [comment] 2024-06-25 11:27
Duplicate of [105](https://github.com/ful1e5/apple_cursor/issues/105). This can be closed.

**Closed** 2024-06-26 06:48 UTC
